platform :ios, 13.0
#use_frameworks!
def main_dependency
  use_frameworks!
pod 'UMengAnalytics-NO-IDFA'
pod 'Bugly'
pod 'SVProgressHUD'
pod 'RxSwift'
pod 'RxCocoa'


end

target "Favorites" do
    main_dependency
end
