platform :ios, 8.0
use_frameworks!
def main_dependency
pod 'UMengAnalytics-NO-IDFA', '~> 4.2.5'
pod 'Bugly', '~> 2.4.7'
pod 'LeanCloud', '~> 10.0.0'
end

target "Favorites" do
    main_dependency
end
